version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: browser-sync
    versions:
    - 2.26.13
  - dependency-name: gulp-pug-linter
    versions:
    - 1.4.0
